### ISSUE TITLE
Table field blank, possibly because of old {{each}} syntax

### ISSUE THREAD

**Issue by Andrew-Max** [DavyJonesLocker/ember-admin-bootstrap#13]
When running `ember serve` I get yelled at: 
```
DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper ('web-ui/templates/admin.hbs' @ L12:C14) is deprecated. Please use the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.
        at /home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:11829:36
        at Walker.visit (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18193:7)
        at visitors.ElementNode (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18209:16)
        at Walker.children (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18226:7)
        at Walker.visit (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18194:12)
        at visitors.ElementNode (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18209:16)
        at Walker.children (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18226:7)
        at Walker.visit (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18194:12)
        at visitors.ElementNode (/home/yotta/git/web-ui/bower_components/ember/ember-template-compiler.js:18209:16)
```

and then  all of the fields on my model  tables are empty: 

![admin_error](https://cloud.githubusercontent.com/assets/4232743/12404362/ca84da8c-be08-11e5-9a2e-df7bd1f400c0.png)

**Comment by bcardarella** [comment]
We're not using this addon anymore, if you'd like to take a stab at the deprecation warnings that would be much appreciated. It shouldn't be too hairy.

**Comment by Andrew-Max** [comment]
good to know. will take a crack at it.

Thanks
